INSERT INTO burgers (burger_name) VALUES ("Bacon Cheeseburger");
INSERT INTO burgers (burger_name) VALUES ("Mushroom Swiss Burger");
INSERT INTO burgers (burger_name) VALUES ("Hamburger");
INSERT INTO burgers (burger_name) VALUES ("Fried Egg Burger");
INSERT INTO burgers (burger_name) VALUES ("Lamb Burger");
INSERT INTO burgers (burger_name) VALUES ("Goat Cheese Burger");
INSERT INTO burgers (burger_name) VALUES ("Salmon Sliders");
INSERT INTO burgers (burger_name) VALUES ("Double Cheeseburger");
INSERT INTO burgers (burger_name) VALUES ("Heart Attack Burger");
INSERT INTO burgers (burger_name) VALUES ("Veggie Burger");
